
CREATE DATABASE postgres_db;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION "pgcrypto";


CREATE TABLE duties(
ID UUID NOT NULL DEFAULT gen_random_uuid(),
NAME TEXT NOT NULL,
CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE FUNCTION
    on_duty_update()
RETURNS
    TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.UPDATED_AT := NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trig_duty_update
BEFORE UPDATE ON duties
FOR EACH ROW EXECUTE FUNCTION on_duty_update();